### ISSUE TITLE
"Back to search results" link [now repeats?]

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#100]
The original Croydon design for directories included a "back to search" results link above the search box

![directory-entry-top](https://user-images.githubusercontent.com/708140/119364251-9ed0a900-bca6-11eb-9d00-f48fe8ef9937.png)

This is shown if a user has reached this page from a directory channel. The link takes them back to the channel with the same facets applied as when they left it

If the user arrived by other means (eg via a Google search) the "back to search results" link is not shown

**Comment by ekes** [comment]
Basically just the browsers back button then.

You can duplicate the browsers back button with javascript simply, it should be possible to restrict this to be displayed if the path looks like one that was the directory landing page.

**Comment by willguv** [comment]
@ekes yep exactly that

**Comment by ekes** [comment]
Seems this might sometimes repeat - looking at demo - 
![image](https://user-images.githubusercontent.com/237186/132840209-5f158b09-a5a6-435b-a6f3-00558d4d72e2.png)
I'd say https://github.com/localgovdrupal/localgov_directories/blob/42fc205fbf34213e534cb012e2547c39c9f9f1f8/js/localgov_directories_entry_search.js#L44 needs a `once`
