### ISSUE TITLE
Install national gazeteer

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#117]
PARK for a directories or forms working group discussion

--------
Croydon and Brighton have previously struggled with address lookups outside their boundaries

For example, for a person moving into the area, their old address may not be within Brighton or Croydon

(I'll find better examples than this)

We briefly explored national databases for land and properties, both badly out of date now

https://data.gov.uk/dataset/03d48dba-529b-4bd5-93a5-6d41d1b20ff9/national-address-gazetteer

https://data.gov.uk/dataset/9231ef97-a965-4d91-97c4-482d33de459a/national-land-and-property-gazetteer

**Comment by ekes** [comment]
I'm guessing this is covered with address completion using any of the paid services which can be plugged in (documentation https://docs.localgovdrupal.org/devs/features/geo-technical.html#configuration ), or the OS Places API will be another plugin, but 'free' to councils option (being written).
