### ISSUE TITLE
OpenReferral: Install config for Directories to use OpenReferral

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#132]

**Comment by ekes** [comment]
- [x] Add form display configuration for the organisation field on venue.
- [x] Write script for population of organisation for existing venues.
- [ ] Decide best way for site builders to trigger autopopulate of organisation for venues _if_ _desired_.
- [ ] Implement decision.
- [x] Document how to add custom fields to open referral mappings.
- [x] Document how to add Open Referral mapping for other (non-venue) custom directory entries.
- [ ] Stop facet mapping config exporting (same as facet config itself).

Stretch goals
- [x] UI with some automation for adding mapping for other non-venue directory entries to open referral.
- [x] UI for adding / altering field mappings of existing directory entries (possibly this is for localgovdrupal/localgov_openreferral itself to offer an admin UI to edit the mapping config entities.

**Comment by ekes** [comment]
> Decide best way for site builders to trigger autopopulate of organisation for venues if desired.

New issue: localgovdrupal/localgov_openreferral#8
