### ISSUE TITLE
 Add class to views for the new localgov_base theme

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_directories#133]
Can we add a class to the view for this display, so the teaser lists render correctly in the new theme (this won't affect any other theme, currently).

- /admin/structure/views/view/localgov_directory_channel

The class needed is `lgd-teaser-list`.

Thanks.

**Comment by finnlewis** [comment]
Did we do this @markconroy ?

**Comment by markconroy** [comment]
I don't think so.
