### ISSUE TITLE
Anonymous classes break code deprecation tests with phpstan-drupal 0.12.11

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_directories#134]
The anonymous class in the `getDirEntryForm` method of the `Drupal\localgov_directories\Plugin\Block\ChannelSearchBlock` class breaks tests with phpstan-drupal version 0.12.11. Works fine with version  0.12.10.

https://github.com/localgovdrupal/localgov_directories/blob/7877f4c15e164b8524df30a0db343865c3621d5e/src/Plugin/Block/ChannelSearchBlock.php#L87

Error is:

```
  ------ ------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_directories/src/Plugin/Block/ChannelSearchBlock.php  
 ------ ------------------------------------------------------------------------------ 
  87     Class                                                                         
         Drupal\localgov_directories\Plugin\Block\AnonymousClass01a859945ded72         
         cee689e1589045065e was not found while trying to analyse it -                 
         discovering symbols is probably not configured properly.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols            
 ------ ------------------------------------------------------------------------------ 
```

Easiest solution is to pin mglaman/phpstan-drupal to 0.12.10 in the project (https://github.com/localgovdrupal/localgov_project/blob/aea2c702b1d4824e6e1fe61d371d283d07491377/composer.json#L26) but it might be better to update the `getDirEntryForm` method so it doesn't use an anonymous class.

@Adnan-cds @andybroomfield @ekes @finnlewis Any thoughts on the best way forward with this? All tests will show as failed until there's a fix for this.

**Comment by stephen-cox** [comment]
I've added a bug report on the drupal-phpstan issue queue: https://github.com/mglaman/phpstan-drupal/issues/194

In the meantime, let's pin the version in the project.

**Comment by finnlewis** [comment]
Thanks @stephen-cox

**Comment by mglaman** [comment]
Sorry for breaking this! I believe I found the culprit and will work on a fix during my next development period (tomorrow)

**Comment by mglaman** [comment]
The release is out which should fix the breakage in 0.12.11: https://github.com/mglaman/phpstan-drupal/releases/tag/0.12.12

Sorry about that!

**Comment by stephen-cox** [comment]
@mglaman Many thanks for the quick fix for this. I'll open another issue to unpin phpstan-drupal.

**Comment by Adnan-cds** [comment]
Thanks a lot Matt.  That was real quick. @mglaman
