### ISSUE TITLE
Demo site: National Parks directory

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#148]
This content has been added to show LocalGov Geo and directory facets in action. There's separate alert banners targeted to the channel page and the venue pages beneath to explain how they work

Here's a sample entry

https://demo.localgovdrupal.org/national-parks-uk/cairngorms

**Comment by willguv** [comment]
@ekes there's an error on the channel page

https://demo.localgovdrupal.org/national-parks-uk

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 196608 bytes) in /var/www/demo.localgovdrupal.org/gitroot/web/core/lib/Drupal/Core/Database/StatementWrapper.php on line 265

(Cheers for your help with the json files)

**Comment by finnlewis** [comment]
Thanks @willguv, there is an issue with the memory limit and lots of large geo area data eating up all the memory.

I've reduced the number of published park 'venues' and increased the memory limit, all seems to be working again now. 

I've logged the memory limit issue here https://github.com/localgovdrupal/localgov_directories/issues/150
