### ISSUE TITLE
Facets 1.x is now unsupported

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#175]
Facets has released 2.0 https://www.drupal.org/project/facets

And 1.x is now marked as unsupported.
<img width="1234" alt="Screenshot 2021-12-15 at 3 01 06 pm" src="https://user-images.githubusercontent.com/1467480/146210393-1f8de0b0-156c-4233-b2e2-de6637692630.png">

**Comment by finnlewis** [comment]
Just discussing this with @ekes and @andybroomfield on our Tech Drop-in.

We will need to investigate and explore upgrading to the 2.x branch.
