### ISSUE TITLE
Proximity searching in SQL backend of Search API 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#189]
@Adnan-cds has been looking at this at Croydon.

Trying to add the location proxiimity search to SearchAPI database backend to allows us to filter by proximity to a location.

See https://lbc-app-w-localgov-corpwebsite-dev5.azurewebsites.net/parking-streets-and-transport/parking/places-park/find-council-car-parks-croydon?search_api_fulltext=&latlon%5Bpostcode%5D=cr0+1ea&latlon%5Bsearch_radius%5D=805 
![image](https://user-images.githubusercontent.com/326588/168605265-601fe55d-22f5-4d7d-8ea2-0eb104d9ef07.png)

We also saw this issue: https://www.drupal.org/project/search_api/issues/2877319

Let us know how you get on @Adnan-cds

**Comment by finnlewis** [comment]
@Adnan-cds has been working on this and has something working. One issue that will present itself is how to hide or remove the exposed views filter on directories that have no location data.

**Comment by andybroomfield** [comment]
This was added in #272
