### ISSUE TITLE
Use an 'and' query between facet groups and 'or' within them. 

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#193]
As the facets are dynamically generated, currently there is a choice in the facets setting for a single block as either 'or' (show results with either facet 1 or facet 2) or 'and' (show results with both facet 1 and facet 2).

However this can be confusing when there are mulktiple groups of facets.
We need to have the option of 'or' within the block, and 'and' between the blocks, whilst maintaining content editors abilitry to create facets.

Eg.  [SEND with over 18 and 16 - 18 checked](https://www.brighton-hove.gov.uk/directories/special-educational-needs-and-disability-send-support?f%5B0%5D=localgov_directories_facets%3A756&f%5B1%5D=localgov_directories_facets%3A3086) compared to [SEND with over 18 and help for child ticked](https://www.brighton-hove.gov.uk/directories/special-educational-needs-and-disability-send-support?f%5B0%5D=localgov_directories_facets%3A1466&f%5B1%5D=localgov_directories_facets%3A3086) the 'just right' entry is visible. Really the logic here should be (age:16 - 18 OR age:over 18) AND (help for:child).

<img width="270" alt="Screenshot 2022-06-13 at 7 16 51 pm" src="https://user-images.githubusercontent.com/1467480/173419261-1a7a96eb-65ae-4d44-8ac2-c6fff2d108bf.png">

It looks like we should be able to do this with a facet pre processer plugin.

**Comment by andybroomfield** [comment]
![And-or-not-2-3234527566](https://user-images.githubusercontent.com/1467480/174080161-1bc88af9-41a2-4c65-a6db-fd61f7d827e3.png)

What we mean by 'And' and 'Or' to avoid confusion.
So by Or, we mean find things that match either, and by And we mean find things that match both.

**Comment by finnlewis** [comment]
@ekes perhaps add your thoughts here for the record!

**Comment by andybroomfield** [comment]
For reference:
- [Custom facet plugin / custom query type](https://www.hook42.com/blog/search-and-facets-and-queries-oh-my)
- [Drupal.org issue that references above](https://www.drupal.org/project/facets/issues/3252122#comment-14353664)
- [Alter query using PreExecuteEventsSubscriber](https://www.drupal.org/project/facets/issues/3182002)
- [Or query type discussion](https://www.drupal.org/project/issues/1217956)

**Comment by andybroomfield** [comment]
From my discovery, and using example in the [Drupal.org issue that references above](https://www.drupal.org/project/facets/issues/3252122#comment-14353664) I was able to alter the string query to achieve the 'and' across groups, 'or' within by separating each facet into a condition group. See below.
So the next stage would be to make this a proper query type plugin and then assign it to the localgov_directory_facets facet.
````php
      // Add the filter to the query if there are active values.
      $active_items = $this->facet->getActiveItems();

      if (count($active_items)) {

        $type_storage = \Drupal::entityTypeManager()
          ->getStorage('localgov_directories_facets');
        $chosen_facets = $type_storage->loadMultiple($active_items);
        foreach($chosen_facets as $directory_facet) {
          $bundle[$directory_facet->bundle()][] = $directory_facet->id();
        }
        foreach($bundle as $bundle_name => $group_items) {
          unset($filter);
          $filter = $query->createConditionGroup($operator, ['facet:' . $field_identifier . '.' . $bundle_name]);
          foreach ($group_items as $value) {
            $filter->addCondition($this->facet->getFieldIdentifier(), $value, $exclude ? '<>' : '=');
          }
          $query->addConditionGroup($filter);
        }
      }
````

**Comment by markconroy** [comment]
Hi All

Any update on this? It's become an issue on the site we are working on for Essex currently. If there's no update, is there anything we can do to progress it?

**Comment by andybroomfield** [comment]
Not had chance to cover as on other projects. 

The code block above does work, but needs to be applied to its own facet / query plugin.
The link to the Drupal issue should be what needs to be done if someone has time to do an implementation.
