### ISSUE TITLE
Remove `Block %block-id is missing.  Cannot update its visibility settings.` error message as it serves no purpose

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_directories#194]
When enabling directories in Microsites two separate error alerts are thrown:

```
 [error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 482 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 482 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
```

Looks related to #43 and #157

```
[error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings. 
```

Looks to be due to https://github.com/localgovdrupal/localgov_directories/blob/0d2d1e51458479c06339a47719d69c283c619649/localgov_directories.module#L229

**Comment by finnlewis** [comment]
We'll just focus on the second error in this issue.

**Comment by stephen-cox** [comment]
The second error message comes from https://github.com/localgovdrupal/localgov_directories/blob/0d2d1e51458479c06339a47719d69c283c619649/localgov_directories.module#L393-L397

This error message serves no purpose as if the block ID is empty (as it is with Microsites) nothing is done. I suggest removing it.
