### ISSUE TITLE
Check url structure for directories

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#23]
[10:43] Callaghan, Will

In Local Gov Drupal, we need to:

- set the url alias at the channel level
- each entry has a 'primary channel' that it derives the url alias from 

I think Ekes has done this already, but we ought to check

**Comment by willguv** [comment]
Hi @ekes we're creating a few final directories in Croydon codebase

(They're schools, so we now know much more about them)

The url aliases are tying us up in knots, and I wanted to check that you'd fixed this in LGD - can you see note above and confirm this is how you've done it

Thanks!

**Comment by ekes** [comment]
That's what it should do. The patterns in as descriptive english as I can make it are:-

For the channels:-
/channel-title
or if the channel is put into a service
/service-parent/channel-title

And for the pages put into the channel:-
/primary-channel-title/page-title
or if the channel is in a service
/primary-channel-service-parent/primary-channel-title/page-title

**Comment by willguv** [comment]
@ekes top work, that's exactly what we need. Sorry to disturb

**Comment by Adnan-cds** [comment]
Thanks @ekes.  ``localgov_directories_pathauto_pattern_alter()`` has made my life easier today :)

**Comment by andybroomfield** [comment]
Just to check that if a prefix of /directories/ was wanted, it could still work that way?

**Comment by ekes** [comment]
Yes you'd put that on the alias of the parent. That's inherited into the pages.

If you put them into services though the service would come first so it would be service-landing-title/directories/channel-title.
