### ISSUE TITLE
 [error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#249]
On a fresh install, I get this: 

```
 [error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings. 
 [error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings. 
 [error]  Block localgov_directories_channel_search_block is missing.  Cannot update its visibility settings. 
```

@ekes @stephen-cox any ideas how to address this?

**Comment by stephen-cox** [comment]
The code that generates this error adds the directory search block to the sidebar of directory content types.

I've proposed removing the error message as it serves no purpose https://github.com/localgovdrupal/localgov_directories/issues/194.

I also wondered about removing all the code that generates this stuff (https://github.com/localgovdrupal/localgov_directories/issues/203), but Andy suggested it was still wanted.

**Comment by finnlewis** [comment]
Thanks @stephen-cox ! It would be really good to fix this, it is a cause for concern for developers installing microsites and seeing red errors! 

I like the idea of following up the suggestion on #194 ?  

I'll create a branch and a PR

**Comment by ekes** [comment]
Merged
