### ISSUE TITLE
Directory Channel - facets appearing that aren't assigned to the channel

### ISSUE THREAD

**Issue by Boosmith** [localgovdrupal/localgov_directories#257]
If you have an organisation in 2 different channels, then the channel page pulls through all the facets from that organisation, whether they are part of the channel on display or not. I suspect this might be just how it works ie. the facets are built up from the organisations returned in the search, rather than which ones were assigned to a channel. However, users have said this is an issue for them. 

The images below show what's going on I hope.
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/6704485/208665178-41496871-ad39-4552-8d7f-5d97ec2e0b93.png)
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/6704485/208665193-6c79b66d-2a96-4153-b431-33502eed9426.png)
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/6704485/208665206-0ccfb534-b8ec-4b23-a751-daf7bdcf1aa1.png)

**Comment by ekes** [comment]
From discussion in slack:-

- My first answer would be, yes you're right, that's how it works. The facets shown are the facets on the results.
- Thanks. I wonder how hard it would be to only show those facets that are in the channel. Not easy would be my guess
- At a visual level I think it would be possible. iirc we are already grouping and sorting the facets in that block. So it would be in there loading the channel from the route; and checking which are associated with the channel. That's my first guess at what the easiest anyway.
- Thanks we'll take a look
- If that works it could be added as an option to the formatter.

**Comment by ekes** [comment]
Do you want to try https://github.com/localgovdrupal/localgov_directories/pull/270

**Comment by ekes** [comment]
#270  merged.
