### ISSUE TITLE
Only install localgov_directories optional config when modules are installed

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#275]
BHCC (and I think others) noticed that an update to 2.5.0 enabled a bunch of optional config in all modules
(Notably the core node book content type and some core image styles we deleted).

See line 80 - 89 in localgov_directories.module

````php
/**
 * Implements hook_modules_installed().
 */
function localgov_directories_modules_installed($modules) {
  $services = in_array('localgov_services_navigation', $modules);
  if ($services) {
    \Drupal::service('config.installer')->installOptionalConfig();
    localgov_directories_optional_fields_settings($services);
  }
}
````

Am I right in thinking that this will install all optional config if the localgov_services_navigation is one of the modules installed.
(I'm assuming this is here so that if localgov_services is enabled after directories, the parent field gets added to the channels.)
However, reading [public function ConfigInstallerInterface::installOptionalConfig](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Config%21ConfigInstallerInterface.php/function/ConfigInstallerInterface%3A%3AinstallOptionalConfig/8.2.x) there are two optional parameters that can be passed (the storage and a dependancy array) that without which all optional config from all modules will be searched through and installed if it can.

As I think the intention here is just to install this modules optional config, we should find a way to limit that.

**Comment by ekes** [comment]
Yep from the docs it looks like we could add dependency array on, I guess best, localgov_service_navigation
