### ISSUE TITLE
Make adding 'facet types' more straightfoward

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#276]
Clicking on "directory facets" in the content sub menu...

![Image](https://user-images.githubusercontent.com/708140/227202985-672207cc-487e-4594-85cb-106b799e96ef.png)

... takes users to this page

![Image](https://user-images.githubusercontent.com/708140/227203046-def88f8b-2c3f-4721-93af-1ac35962de4c.png)

- Facets can be added here
- Facet types cannot

To add a facet type, users need to go to the top left content menu and navigate from there

![Image](https://user-images.githubusercontent.com/708140/227203073-78f928a5-1803-4d24-be4b-18199bcba6f0.png)

How can this be made more straightforward?

**Comment by willguv** [comment]
@stephen-cox this feels like a trivial fix - is it?

Many thanks!

**Comment by stephen-cox** [comment]
@willguv It's easy to add a 'Add directory facet type' button to the top of the page next to the 'Add directory facet' button.

It might be worth overhauling the UX of managing directory facets entirely, so they're managed more like taxonomy terms. There would be a page that lists all the types, clicking on one would take you to another page where all the facets for that type can be managed. This approach isn't really compatible with having directory facets managed through the content overview pages though as these are views of content.

That said, we can do both. Keep the content page and add a button to add new types while creating a more intuitive way to manage directory facets.

**Comment by willguv** [comment]
@stephen-cox if it's quick, can you add the 'add directory facet type' button and I'll write another card to consider the UX of directory facets. Thanks again

**Comment by stephen-cox** [comment]
@willguv PR #277 adds this button so the directory facet management page looks like

![image](https://user-images.githubusercontent.com/7189914/230363532-45ecb895-9bb7-4f29-966f-626ad82f76ef.png)

The one issue I see with this is that once you've added a new directory facet type you are redirected to the directory facet type management page (/admin/structure/localgov_directories_facets_types) and so to start adding new facets of this type you'll need to go back to the directory facet management page.

I'm not sure there's an easy fix for this.

**Comment by willguv** [comment]
Thanks @stephen-cox. I'm away from my computer for a couple of days so will have a look when I return

**Comment by andybroomfield** [comment]
Maybe add a ?destination= query string to the add facet type link?

**Comment by stephen-cox** [comment]
> Maybe add a ?destination= query string to the add facet type link?

The problem with this is the button links are generated by Drupal so we'll need to hook into things to change this. There's then the question of whether we always want to redirect to the facets page after adding a type? If not, we need to add logic to decide when to add the destination parameter.

Rather than spending too much time on this I think it would be better to overhaul how directory facets are managed in general. As I've already done this for Microsites it's now going to be huge job.

**Comment by willguv** [comment]
@stephen-cox OK let's discuss - I've messaged you

**Comment by willguv** [comment]
Covered in https://github.com/localgovdrupal/localgov_directories/pull/277
