### ISSUE TITLE
Tests fail which break tests for all repos

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_directories#28]

**Comment by finnlewis** [comment]
I've been looking at the schema test failures, alongside @stephen-cox 

It looks like: 

 - The schema that is failing is that of the exported view's attachment view that provides the leaflet map
 - The schema appears to be defined here https://git.drupalcode.org/project/leaflet/-/blob/2.0.x/modules/leaflet_views/config/schema/leaflet_views.style.schema.yml
 - Installing config_inspector and going to https://localgov.lndo.site/admin/reports/config-inspector/views.view.localgov_directory_channel/list gives us a list of the missing schema: 

```

display.node_embed_map_attachment.display_options.style.options.data_source | Undefined | undefined | location | missing schema
-- | -- | -- | -- | --
  | display.node_embed_map_attachment.display_options.style.options.entity_source | Undefined | undefined | __base_table | missing schema
  | display.node_embed_map_attachment.display_options.style.options.entity_source_submit | Undefined | undefined | Update Entity Source | missing schema
  | display.node_embed_map_attachment.display_options.style.options.name_field | Undefined | undefined | title | missing schema
  | display.node_embed_map_attachment.display_options.style.options.description_field | Undefined | undefined | search_api_rendered_item | missing schema
  | display.node_embed_map_attachment.display_options.style.options.view_mode | Undefined | undefined | full | missing schema
  | display.node_embed_map_attachment.display_options.style.options.leaflet_map | Undefined | undefined | OSM Mapnik | missing schema
  | display.node_embed_map_attachment.display_options.style.options.height | Undefined | undefined | 400 | missing schema
  | display.node_embed_map_attachment.display_options.style.options.height_unit | Undefined | undefined | px | missing schema
  | display.node_embed_map_attachment.display_options.style.options.hide_empty_map | Undefined | undefined | 1 | missing schema
  | display.node_embed_map_attachment.display_options.style.options.disable_wheel | Undefined | undefined | 0 | missing schema
  | display.node_embed_map_attachment.display_options.style.options.fullscreen_control | Undefined | undefined | 1 | missing schema
  | display.node_embed_map_attachment.display_options.style.options.gesture_handling | Undefined | undefined | 0 | missing schema
  | display.node_embed_map_attachment.display_options.style.options.reset_map | Undefined | undefined | <array> | missing schema
  | display.node_embed_map_attachment.display_options.style.options.map_position | Undefined | undefined | <array> | missing schema
  | display.node_embed_map_attachment.display_options.style.options.icon | Undefined | undefined | <array> | missing schema
  | display.node_embed_map_attachment.display_options.style.options.path | Undefined | undefined | {&quot;color&quot;:&quot;#3388ff&quot;,&quot;opacity&quot;:&quot;1.0&quot;,&quot;stroke&quot;:true,&quot;weight&quot;:3,&quot;fill&quot;:&quot;depends&quot;,&quot;fillColor&quot;:&quot;*&quot;,&quot;fillOpacity&quot;:&quot;0.2&quot;} | missing schema
  | display.node_embed_map_attachment.display_options.style.options.geocoder | Undefined | undefined | <array>

```

I've tried: 
 - re-exporting the views config and re-installing
 - moving the defined schema to other files in core, in case it is not getting picked up by that file for any reason
 - playing with the formatting of the schema, adding in an 'options' parent for example

All very confusing and frustrating.

Anything to add from your investigations @stephen-cox

**Comment by finnlewis** [comment]
I've also tried changing the view from an attachment view to a block view, re-exporting and re-installing from config, in case it is a quirk of views attachments. Still the same 'missing schema' errors.

**Comment by finnlewis** [comment]
I've confirmed this on a vanilla install and posted my findings on the issue that @stephen-cox has already posted a patch to: https://www.drupal.org/project/leaflet/issues/2883700#comment-13817106

**Comment by stephen-cox** [comment]
It certainly seems like the [leaflet_views.style.schema.yml](https://git.drupalcode.org/project/leaflet/-/blob/2.0.9/modules/leaflet_views/config/schema/leaflet_views.style.schema.yml) file should be providing some of the missing schema. It's providing schema for the `leaflet_map` views style plugin as defined in the [LeafletMap](https://git.drupalcode.org/project/leaflet/-/blob/2.0.9/modules/leaflet_views/src/Plugin/views/style/LeafletMap.php) class.

The problem is this schema file is not being applied even though it is incomplete.

I have tried renaming the file and copying its contents into other files as well as stripping it right back along with the [views.view.localgov_directory_channel.yml](https://github.com/localgovdrupal/localgov_directories/blob/master/modules/localgov_directories_location/config/override/views.view.localgov_directory_channel.yml#L429) file. But none of this works, which makes me think we're missing something more fundamental.

**Comment by Adnan-cds** [comment]
Sorry Finn, I haven't had the chance to look into it at all.  The Drupal [documentation for config schema](https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-schemametadata#use) says strict schema check can be turned off in a test by adding ```protected $strictConfigSchema = FALSE;```.  It does not recommended this of course. Since these schema issues are breaking all our test runs, we can consider this as a last resort.

@finnlewis @stephen-cox

**Comment by Adnan-cds** [comment]
Hi Finn,
This issue is resolved now, right?

@finnlewis @stephen-cox
