### ISSUE TITLE
(Directories) Search and Facet component page positioning

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_directories#30]
For the main theme, we require the 'search' and 'facet' components to be rendered into the 'sidebar' area of the page template for all directory templates. For Directory Channel, currently the search and facet components are intertwined with the Directory listings and rendered within the 'body'. For the Directory Venue template we dont see these options at all.

**Comment by andybroomfield** [comment]
From memory, these are rendered as psudeo fields rather than a block. 
We could look at how to render the EVA view exposed form as a block (not directly supported if I remember correctly) or Use layout builder or in the theme to push render the form seperatly.

**Comment by finnlewis** [comment]
From standup: Adnan has been having trouble with this. Placing the block contnent in the sidebar is not working.
Drupal is attempting to render the block in a clever / lazy loading manner, so the page template does not know if it has a sidebar or not. 

This is a common approach, but maybe it needs to be reviewed.

@Adnan-cds is trying work arounds.... like pre-rendering.... but this breaks.

@Adnan-cds could you document the issue in a bit more detail and we're see if we can get some other help?

**Comment by Adnan-cds** [comment]
Blocks employ [lazy building](https://www.drupal.org/docs/8/api/render-api/auto-placeholdering).  This makes it difficult to determine from **Twig templates** if they will eventually produce empty content or not.  [Relevant code from our page template.](https://github.com/localgovdrupal/localgov_theme/blob/231234f2cb87663dce89445a6a80edf059e4b6bc/templates/system/page.html.twig#L53)

Relevant links:
- Drupal core issue: https://www.drupal.org/node/953034
- I tried this work around which caused other issues: https://www.drupal.org/forum/support/module-development-and-code-questions/2016-04-07/drupal-8-regions-with-and-empty#comment-12149518 

But a slight modification of the above work around is giving expected results.  I have just raised a [pull request](https://github.com/localgovdrupal/localgov_theme/pull/73/files) to help **review** the situation.

@andybroomfield @finnlewis @stephen-cox @cjstevens78
