### ISSUE TITLE
CQC widget - add as a resusable field widget

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#302]
Greenwich need to add a widget to demonstrate the CQC compliance. 

Sounds like this might be useful for other councils.

@ekes do we have more information yet?

**Comment by finnlewis** [comment]
It might look something like this
![image](https://github.com/localgovdrupal/localgov_directories/assets/326588/486ea353-3c5e-4161-8434-0b20ab1641ea)

**Comment by ekes** [comment]
Think it's just this https://www.cqc.org.uk/guidance-providers/ratings/using-cqc-widget-troubleshooting

My idea was to make it reusable. To create a field (extending string) for the CQC code, with an additional field formatter that add the JS and renders the widget for the ID.

I'm guessing it's most relevant for directories, but it could just go somewhere as a field type that can be enabled on any content type should it be possible it could be used elsewhere.

**Comment by andybroomfield** [comment]
Closing as the module is https://github.com/localgovdrupal/localgov_cqc if anyone needs it.
