### ISSUE TITLE
Excluding facet types from configuration export breaks deployments and site-install

### ISSUE THREAD

**Issue by Polynya** [localgovdrupal/localgov_directories#311]
I don't understand why facet types are excluded from config export. The readme says:

_They are intended for creation and management by content editors on the production site. Adding a facet type will automatically make it available on Directory Channels, and add any values to the Facet block on the page, without any additional site building. As such by design they are excluded from configuration export._

If I add a field to the facet type or create a view then these will be exported with a dependency on the facet type. I can't import the config into another environment without manually creating the facet type. Also, `drush site-install --existing-config` will fail.

These problems are fixed by manually creating the facet type YML file in the config folder.

**Comment by andybroomfield** [comment]
@Polynya This [can be enabled in settings.php](https://github.com/localgovdrupal/localgov_directories/blob/8102ef733b7c5938dd81660ea1b0cc5401db8b48/src/EventSubscriber/DirectoriesConfigSubscriber.php#L84C8-L84C59).

```php
$settings['localgov_directories_stage_site'] = TRUE;
```

As mentioned in the readme, their not exported as content designers can (by default) make arbitrary facet types for including on directories which would get wiped out during config imports, they are treated as if they where content.

**Comment by ekes** [comment]
Also as per https://github.com/localgovdrupal/localgov_directories/blob/8102ef733b7c5938dd81660ea1b0cc5401db8b48/README.md#using-taxonomy-term-facets I would advise if you want a controlled exportable set of taxonomy types it's best to use a taxonomy.

**Comment by Polynya** [comment]
Thanks @andybroomfield and @ekes, I should have read further on in the readme :)
