### ISSUE TITLE
Sort Facet items by weight

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_directories#35]
A weight property should allow us to manually order Facet type and Facet items.  At the moment these are ordered alphabetically.

Sub tasks:
- [x] Add *weight* property to the *localgov_directories_facets* and *localgov_directories_facets_type* config entities.
- [x] Update [Drupal\localgov_directories\LocalgovDirectoriesFacetsListBuilder](https://github.com/localgovdrupal/localgov_directories/blob/master/src/LocalgovDirectoriesFacetsListBuilder.php) and [Drupal\localgov_directories\LocalgovDirectoriesFacetsTypeListBuilder](https://github.com/localgovdrupal/localgov_directories/blob/master/src/LocalgovDirectoriesFacetsTypeListBuilder.php) to use these weight values when listing their respective entities.
- [x] A Facet sort plugin that sorts based on the weight property instead of the current *Sort by display value*.
- [x] Update the Facet related config files.

**Comment by finnlewis** [comment]
Note: @stephen-cox thinks this might be harder than it sounds!
