### ISSUE TITLE
Display of directory items on channel page should use teaser display mode

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_directories#38]
As mentioned in point 5 on https://github.com/localgovdrupal/localgov_theme/issues/85, the display of directory items on a channel page should use the node teaser view instead of the default view.

There is some code that sets this, but this was commented out because it breaks the tests: https://github.com/localgovdrupal/localgov_directories/blob/27112a3a05689588a6ed7f641a0332ef52d948ec/localgov_directories.module#L154-L170

The reason it's done in code rather than in the view configuration is because we don't know which directory item node types are installed when enabling the module.

**Comment by stephen-cox** [comment]
@cjstevens78 @Adnan-cds This is the issue we were just discussing at standup

**Comment by Adnan-cds** [comment]
Thanks Steve :)  I will see if I can do anything about it.
