### ISSUE TITLE
Investigate abstracting directories facets functionality to a 'Finder' module

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#402]
@willguv mentioned that gov.uk uses the term 'Finder'

Worth a look: https://github.com/alphagov/finder-frontend?tab=readme-ov-file

People on the meeting today seemed happy with the term 'finder' 

@ekes is going to investigate what we might abstract from directories into another module, which can then be used in events and news etc.

**Comment by andybroomfield** [comment]
BHCC use of facets.
Currenty - Directories and events (use of event channel nodes).

Future
Form finder - List of all forms (webform).
Location finder - Simple directory (no actual page, just geos) Recyclicng bins / communial bins

**Comment by finnlewis** [comment]
@ekes  has made a start on this investigation, and created other related issues as they crop up

 - https://github.com/localgovdrupal/localgov_finders/issues/1 
 - https://github.com/localgovdrupal/localgov_finders/issues/2

**Comment by willguv** [comment]
We agreed 4 Nov that this is the approach being taken, and coding is already underway
