### ISSUE TITLE
Non-existent localgov_directory_channels field leading to errror msg in fresh install

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_directories#43]
### Severity
Minor

### How to reproduce
- Install the localgov_directories module.
- Check the watchdog for "error" messages.  There should be two messages from the search_api module.

### Error messages
- Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field ''Directory channels'' on index ''Directories''. in Drupal
- Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field ''Directory channe

### Work around
Install localgov_direcotories_page/localgov_directories_location/localgov_directories_venu module.  Or create a content type and attach the existing localgov_directory_channels field to it.

### Possible cause
When the localgov_directories module is first installed, there are no content types acting as a Directory entry.  This means the *localgov_directory_channels* field is not attached to any content type.  But the **search_api.index.localgov_directories_index_default.yml** config file is already referring to the localgov_directory_channels field.

### Possible fix
We dealt with a similar issue in #38 where the non-existent *localgov_directory_facets_select* field led to more severe conditions.  To resolve that, we removed any mention of localgov_directory_facets_select from search_api.index.localgov_directories_index_default.yml.  It was then added back programmatically when this field was added to a Content type for the first time. @see [localgov_directories_field_config_insert()](https://github.com/localgovdrupal/localgov_directories/blob/6d552dd0a2836bd4dc949461915434219018e4a6/localgov_directories.module#L117)

**Comment by ekes** [comment]
Added the similar assumption in localgov_events.

The fact that the directories content type also requires directory channels is also possibly incorrect. I've just created one where all the filtering - so far - that is requested is on location, so no channel.

**Comment by keelanfh** [comment]
Does not seem to be happening now, so closing.
