### ISSUE TITLE
Better Facet markup

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_directories#45]
Current Facet markup generated by the [facets-item-list--links--localgov-directories-facets.html.twig](https://github.com/localgovdrupal/localgov_directories/blob/2b24950cc6e9c6f45829ef7fdc66ec0c6197407f/templates/facets-item-list--links--localgov-directories-facets.html.twig#L48) template does not entirely conform to the HTML5 convention.  It has ul elements as direct children of another ul element.  But ul elements can only have *li*, *script*, and *template* elements as [direct children](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul).  Sample markup:
```
<ul class="...">
    <li><h4>First facet title</h4></li>
    <ul class="...">
        <li>Facet item 0</li>
        <li>Facet item 1</li>
        ...
    </ul>

    <li><h4>Second facet title</h4></li>
    <ul class="...">
        <li>Facet item A</li>
        <li>Facet item B</li>
        ...
    </ul> 
</ul>
```
A better markup would have the inner ul element moving inside its corresponding li element.  So the above markup should look like the following:
```
<ul class="...">
    <li>
        <h4>First facet title</h4>
        <ul class="...">
            <li>Facet item 0</li>
            <li>Facet item 1</li>
            ...
        </ul>
    </li>

    <li>
        <h4>Second facet title</h4>
        <ul class="...">
            <li>Facet item A</li>
            <li>Facet item B</li>
            ...
        </ul>
    </li> 
</ul>
```

@stephen-cox @cjstevens78

**Comment by markconroy** [comment]
I came to post the exact same issue, but to suggest different mark up.

I think markup like this might make more sense.

```
<div class="facets">
  <h3 class="facets__title>Facet Title 1</h3>
  <ul class="facets__list">
    <li class="facets__list-item">
      <a class="facets__link">Primary School</a>
    </li>
    <li class="facets__list-item">
      <a class="facets__link">Secondary School</a>
    </li>
  <ul>
  <h3 class="facets__title>Facet Title 2</h3>
  <ul class="facets__list">
    <li class="facets__list-item">
      <a class="facets__link">Private School</a>
    </li>
    <li class="facets__list-item">
      <a class="facets__link">Public School</a>
    </li>
  <ul>
</div>
```

**Comment by cjstevens78** [comment]
@Adnan-cds @markconroy  I agree it doesn't make much sense to have the the facet parent container as a  list and would generally go with what Mark has suggested above however, id be wary of introducing this BEM 'everythings got a class' approach when no other modules have it - unless they are all being re-written as part of the wider re-structuring?

**Comment by markconroy** [comment]
If we have a template and the ability to add a class, we might as well. If we are not writing a template (and maybe this template is not needed at all), then it would make sense to just use Drupal classes whatever they may be.

**Comment by andybroomfield** [comment]
Did this get resolved?

**Comment by Adnan-cds** [comment]
This appear to have been [resolved](https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/misc/facets-item-list.html.twig).
