### ISSUE TITLE
Pager not showing the full amount of items

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov_directories#56]
I notice that when using a full pager on the list view it doesn't show all the items and instead shows up to the current page. So if have 10 pages of items, on page 1 you'd only see 2 pages in the pager instead of all 10.

The fix is to change the pager id in the view to 1 instead of the default 0.

**Comment by tanc** [comment]
```
--- a/config/sync/views.view.localgov_directory_channel.yml
+++ b/config/sync/views.view.localgov_directory_channel.yml
@@ -620,7 +620,7 @@ display:
         options:
           items_per_page: 10
           offset: 0
-          id: 0
+          id: 1
           total_pages: null
           tags:
             previous: ‹‹
```

**Comment by andybroomfield** [comment]
Belive this is fixed in current, can anyone confirm?

**Comment by andybroomfield** [comment]
Is working for me, so I'm going to close this issue for now, please re-open or create a new issue if this re-occurs.
