### ISSUE TITLE
Back end: Rename "Directory" tab "Channels and facets"

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#72]
On "directory venue" and "directory page" content types, the "Directory" channel does not describe the options beneath

We should call this tab "Channels and facets" as they're the options a content designer can select from

See screenshots for an example

**Comment by willguv** [comment]
<img width="1233" alt="Directory tab" src="https://user-images.githubusercontent.com/708140/110492320-fae55180-80e9-11eb-9a61-47affe878fe6.png">
<img width="1246" alt="Directory tab 2" src="https://user-images.githubusercontent.com/708140/110492327-fc167e80-80e9-11eb-8235-c7f1a44015fe.png">

**Comment by stephen-cox** [comment]
Possible fix for this in PR #82
