### ISSUE TITLE
Configure Search API DB to deliver more useful results

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#73]
Croydon Hotjar data suggests that search takes 10% of the clicks on a typical landing page, but we've anecdotal evidence that the results aren't as good as they could be

Examples:

"aero drome" won't find "aerodrome"

"children's" won't find "children"

## Discussed with @stephen-cox and @ekes on 21 May

Search API DB allows basic fixes for:

- stemming/ plurals
- ignoring apostrophes
- ignoring spaces

Let's also check what's being indexed to give us the best results we can

##Later

Let's write something about the limitations of the built in search, and how it could be extended with a separate search service. Could talk to Waltham Forest as they're experimenting with Solr

**Comment by willguv** [comment]
Search API DB allows basic fixes for

stemming/ plurals
ignoring apostrophes
ignoring spaces

Let's also check what's being indexed to give us the best results we can

**Comment by ekes** [comment]
> "children's" won't find "children"

Test confirms that with the default configuration the body text, or title, including _children's_ is returned for the search _child_ and _children_.
And vice versa _children's_ and _childrens_ search find _children_.

> "aero drome" won't find "aerodrome"

_Aero_ and _Aerodrome_ and _Aero Drome_ found _Aerodrome_; _Drome_ alone doesn't.

Could the examples be an issue with a specific site configuration, are these string in different fields, or searched with "" marks? Are there other examples?

There are however additional strings included in the search (like the titles of fields) and it should be checked if all the fields are correctly displayed, so I'll make a PR for those.

**Comment by willguv** [comment]
Thanks @ekes. This issue was raised in a Croydon content design meeting a while ago, and I think @benhillsjones mentioned it. 

Ben and I are catching up today and I'll raise it then. Or Ben, you can add extra info here if you have it

**Comment by andybroomfield** [comment]
Closing as the merged PR should fix some of this. We have other open issues for improving search.
