### ISSUE TITLE
Summary field should be open by default

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#86]
The directory channel page provides a better experience for users if summary content is written by a content designer

At present, the summary field is hidden by default. A content designer has to click "edit summary" to see it

See https://localgovdrupal.agile.coop/node/add/localgov_directories_venue

The summary field should be open by default

-- Later --

We should review all content formats to decide whether all summary fields need to be open and mandatory by default

**Comment by ekes** [comment]
Is open by default.
