### ISSUE TITLE
Back end: Fix map display on venue tab

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#87]

**Comment by willguv** [comment]
Create a new directory venue type at https://localgovdrupal.agile.coop/node/add/localgov_directories_venue

Click on the "venue" tab

The map seems to be misbehaving at lower screen resolutions

This is what I see on my laptop

![1](https://user-images.githubusercontent.com/708140/118805756-35176000-b89e-11eb-951e-ed6bc01ec0b7.png)

![2](https://user-images.githubusercontent.com/708140/118805771-39437d80-b89e-11eb-85f8-879b1434ade0.png)

A content designer can't check the accuracy of the pin. They also can't move the pin or drop a new one without resizing the map, scrolling it

I discovered that making my browser window smaller fixes the problem

![3](https://user-images.githubusercontent.com/708140/118806034-84f62700-b89e-11eb-8277-a269b5ad923a.png)

Can someone replicate and attempt a fix? Thanks

**Comment by finnlewis** [comment]
@markconroy is this something you can help us with ? It looks like a gnarly problem with positioning calculation for the map container. @ekes looked at this and it all got a bit heavy!

**Comment by willguv** [comment]
In addition, this was a separate issue but it's related

## Remove excessive borders on map UX #96 

On https://localgovdrupal.agile.coop/node/69/edit?destination=/admin/content the map window is surrounded by 4 borders - a bit excesssive

Is there a technical reason for this? Can we remove some of them?

**Comment by markconroy** [comment]
Do we know if this issue is coming from the Drupal module or from our theme? Judging by the screenshots it's coming from the module or the Claro theme.

**Comment by finnlewis** [comment]
Good question @markconroy. I suspect it is the Drupal module and / or field group tabs and / or Claro theme.

**Comment by markconroy** [comment]
That issue with the map looking funky in the location field of a venue node is one I have seen before. It’s happened to us when trying to load a map inside a vertical tab. Check out this for a cool way to mess with your head:
- Open /node/add/localgov_directories_venue
- Click on the location tab
- Map looks funny
- Right click on map and inspect element
- Map now looks fine
- Opening inspector causes a layout shift and the map then loads correctly (you can also force it to fix by making you browser 1px smaller)

I think our fix for it in annertech was to not have the map field in a tab. Is that feasible here? If you move the location field on the “Manage form display” of the venue content type outside of the tabs, it seems to work fine again.

**Comment by markconroy** [comment]
Here we go. We need to invalidate the map size when the tab is opened. Currently when the map loads initially the size is not set since the tab is closed.

https://stackoverflow.com/questions/36246815/data-toggle-tab-does-not-download-leaflet-map

**Comment by ekes** [comment]
No longer required as the map is now in the entity browser.
