### ISSUE TITLE
Back end: Move accessibility field down the page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#89]
On https://localgovdrupal.agile.coop/node/46/edit?destination=/admin/content, venue tab

1) Move the "accessibility" field down the page to between opening times and notes

2 Change the title of the field to "Venue accessibility"

This puts the map and address next to each other, and lists the optional info fields in the correct order

**Comment by willguv** [comment]
Agreed with @ekes and @stephen-cox to put accessibility under map/ address

**Comment by ekes** [comment]
Order for the Address bundle is now: Address, Map, Accessibility.
