### ISSUE TITLE
Search panel appears twice on Directory channel

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#93]
See https://localgovdrupal.agile.coop/adult-health-and-social-care/money-employment-and-training-directory

The search panel should appear in the left hand column, not in the main column

**Comment by finnlewis** [comment]
@ekes has tried to replicate this problem, without success so far.

**Comment by willguv** [comment]
@Adnan-cds may have started this

**Comment by Adnan-cds** [comment]
I remember we had this issue for a short while.  I can see that https://localgovdrupal.agile.coop is not using the latest code of the localgov_directories module.  Perhaps a code deployment will resolve this.
