### ISSUE TITLE
Channel dropdown issue on Directory venue and Directory page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#94]
On https://localgovdrupal.agile.coop/adult-health-and-social-care/money-employment-and-training-directory/get-online-home and https://localgovdrupal.agile.coop/localgov-drupal-collaborators/annertech the search panel in the left hand column includes a channel drop down menu

eg

<img width="584" alt="Screenshot 2021-05-20 at 18 10 43" src="https://user-images.githubusercontent.com/708140/119020949-c0741c80-b996-11eb-8836-1a278d57ac16.png">

This drop down menu should only appear in the page or venue is included in multiple channels. Both of the examples are only in one channel, so the drop down menu should not appear.

Separately I'm not convinced by this pattern, and we should include in user testing. For now, we need to fix the issue.

**Comment by finnlewis** [comment]
@ekes suggests that we change the drop down to just text if there is only one option.

If there are multiple, the drop down should show

**Comment by willguv** [comment]
@ekes I've looked at the original pattern, as designed by @clearspotmedia 

<img width="189" alt="directory-search-box" src="https://user-images.githubusercontent.com/708140/119363836-2b2e9c00-bca6-11eb-8c58-709e4a369eb5.png">

If a venue or page is in more than one channel, the "in" and drop down menu appear

If it's not, they're hidden

What do you think?

**Comment by willguv** [comment]
This hasn't had a lot of testing, but think it's a step forward from what we have. I'd like us to run some exhaustive testing on Directories, and this is the pattern I'd like included in those tests
