### ISSUE TITLE
Not able to create a directory venue as map UX has disappeared

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#95]
See https://localgovdrupal.agile.coop/node/add/localgov_directories_venue, click on venue tab

Other venues seem to have no map either https://localgovdrupal.agile.coop/node/51/edit

<img width="1062" alt="Screenshot 2021-05-20 at 18 37 39" src="https://user-images.githubusercontent.com/708140/119024140-ab998800-b99a-11eb-9c22-ff16df62d80f.png">

## Update

Maps are not visible to content designers, but they should be

Logging in as admin fixed the problem

<img width="1054" alt="Screenshot 2021-05-20 at 18 40 37" src="https://user-images.githubusercontent.com/708140/119024368-e56a8e80-b99a-11eb-9bc9-8e02d697e06c.png">

**Comment by ekes** [comment]
By default a 'Content Disigner' can't create Directory content, nor Geo content. So I assume in the example above they have been given permission to create a 'Venue' but not been given permission to create a Geo Place to associate with this.

Do we:
 (a) want to give content designers default permissions over Directories. If so how much? All of:- Channels; Pages; Venue; Facet Types; Facets. Or do we rather that Directories has it's own roles that cover some / all of these. This I'm not sure what the answer is.
 (b) do we want content designers by default to be able to create, update, delete Geo Locations. That I'm guessing is a yes.

**Comment by willguv** [comment]
@ekes content designers need to be able to create, edit and publish all types of directories content.

Croydon has these permission now and use them all the time. While I was there, Brighton content designers created everything they could too. (Creating facets wasn't available until you built them, but was always part of the plan).

At a later date, we may well want to give permissions for third parties to create, edit and publish. Brighton has at least one directory of this kind.

We also discussed encouraging users to update their own entries, and the central team of content designers approving them. This missed the cut towards the end of the project.

If it's not a lot of effort to add new permissions, I'd prefer to leave these until we have a Directories working group and real examples to look at.

**Comment by ekes** [comment]
So there's a fix for #30 which blocks this till it's in. Once it's in we can implement the hook here (and in geo) and have the defaults fixed.

**Comment by ekes** [comment]
localgovdrupal/localgov_core#30 is now in. 

To do implement default permissions in this (and geo) modules.

**Comment by stephen-cox** [comment]
Done - sprint 6
